<?php
$section->addPageBreak();
$section->addTitle("REFERÊNCIAS", 1);

$fontStyleReferencias = array('name' => 'arial', 'size' => 10);

//Texto
$myTextElement = $section->addText('ABHO - Associação Brasileira de Higienistas Ocupacionais. Definição de higiene ocupacional. Disponível em: http://www.abho.org.br/abho/. Acesso em: 23 de julho de 2018.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('AGAHNEJAD, Payman. Análise ergonômica no posto de trabalho numa linha de produção utilizando método NIOSH: um estudo de caso no pólo industrial de Manaus. 2011. 92 f. Dissertação (Mestrado) - Universidade Federal do Pará, Instituto de Tecnologia, Belém, 2011. Programa de Pós-Graduação em Engenharia Elétrica.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('AMORIM. E. L. C. Apostila de Ferramentas de Análise de Risco. Maceió: UFAL, 2013. Disponível em: https://sites.google.com/site/elcaufal/disciplinas/programacao-estruturada. Acesso em: 23 julho de 2018.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('ARRUDA, Heder Jobbins de. Elaboração de mapas de riscos para os laboratórios de química da UTFPR Câmpus Ponta Grossa. 2015. 67 f. Trabalho de Conclusão de Curso (Graduação) - Universidade Tecnológica Federal do Paraná, Ponta Grossa, 2015.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('BRASIL – Ministério do Trabalho - MTb. Portaria 3.214, de 08/06/1978. Normas Regulamentadoras - NR. Diário Oficial da União, Brasília, DF, 08 jun. 1978. Disponível em: https://www.camara.gov.br/sileg/integras/839945.pdf. Acesso em: 23 de julho de 2018.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('BRASIL. Norma Regulamentadora 07 - Programa de Controle Médico de Saúde Ocupacional. Disponível em: https://enit.trabalho.gov.br/portal/images/Arquivos_SST/SST_NR/NR-07.pdf.  Acesso em: 23 de janeiro de 2020.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('BRASIL. Norma Regulamentadora 09 - Programa de Prevenção de Riscos Ambientais. Disponível em: https://enit.trabalho.gov.br/portal/index.php/seguranca-e-saude-no-trabalho/sst-menu/sst-normatizacao/sst-nr-portugues?view=default.  Acesso em: 23 de janeiro de 2020.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('BRASIL. Ministério do Trabalho e Emprego. Portaria 485, de 11 de novembro de 2005. Dispõe sobre a Norma Regulamentadora 32 - Segurança e Saúde no Trabalho em Estabelecimentos de Assistência à Saúde.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('BRASIL. Norma Regulamentadora15 - Atividades e Operações Insalubres. Disponível em: https://enit.trabalho.gov.br/portal/images/Arquivos_SST/SST_NR/NR-15-atualizada-2019.pdf.  Acesso em: 18 de janeiro de 2020.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('BRASIL. Norma Regulamentadora15 - Atividades e Operações Insalubres – Anexo Nº 1. Disponível em: https://enit.trabalho.gov.br/portal/images/Arquivos_SST/SST_NR/NR-15-Anexo-01.pdf.  Acesso em: 23 de janeiro de 2020.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('BRASIL. Norma Regulamentadora15 - Atividades e Operações Insalubres – Anexo Nº 9. Disponível em: https://enit.trabalho.gov.br/portal/images/Arquivos_SST/SST_NR/NR-15-Anexo-09.pdf.  Acesso em: 18 de março de 2020.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('BRASIL. Norma Regulamentadora 16 - Atividades e Operações Perigosas. Disponível em: https://enit.trabalho.gov.br/portal/images/Arquivos_SST/SST_NR/NR-16-atualizada-2019.pdf.  Acesso em: 18 de janeiro de 2020.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('BRASIL. Norma Regulamentadora 17 - Ergonomia. Disponível em: https://enit.trabalho.gov.br/portal/images/Arquivos_SST/SST_NR/NR-17.pdf.  Acesso em: 18 de janeiro de 2020.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('BRASIL. Norma Regulamentadora 32 - Segurança e Saúde no Trabalho em Serviços de Saúde. Disponível em: https://enit.trabalho.gov.br/portal/images/Arquivos_SST/SST_NR/NR-32.pdf.  Acesso em: 23 de janeiro de 2020.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('BRASIL. Presidência da República. Casa Civil. Subchefia para Assuntos Jurídicos. LEI Nº 6.514, DE 22 DE DEZEMBRO DE 1977. Altera o Capítulo V do Título II da Consolidação das Leis do Trabalho, relativo a segurança e medicina do trabalho e dá outras providências. Disponível em:  http://www.planalto.gov.br/ccivil_03/leis/L6514.htm. Acesso em: 23 de julho de 2018.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('CAIRO JUNIOR, José. O acidente de trabalho e a responsabilidade civil do empregador. São Paulo: LTR, 2003 apud MELO, Raimundo Simão de. Direito ambiental do trabalho e a saúde do trabalhador. 4. ed. São Paulo: LTR, 2010.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('CETESB, Companhia de Tecnologia de Saneamento Ambiental do Estado De São Paulo. Manual de Orientação para a Elaboração de Estudos de Análise de Riscos. São Paulo, 2012.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('COCHARERO, R. Ferramentas para gestão de segurança e saúde no canteiro de obras. 2007. 109 f. Monografia (MBA em Tecnologia e Gestão na Produção de Edifícios) – Escola Politécnica, Universidade de São Paulo, São Paulo, 2007.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('FIOCRUZ – Fundação Osvaldo Cruz. Riscos de Acidentes. http://www.fiocruz.br/biosseguranca/Bis/lab_virtual/riscos_de_acidentes.html. Acesso em: 23 de janeiro de 2020.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('FIOCRUZ – Fundação Osvaldo Cruz. Tipos de Riscos. Riscos e seus agentes: Riscos Ergonômicos. http://www.fiocruz.br/biosseguranca/Bis/virtual%20tour/hipertextos/up1/tipos_de_riscos.html. Acesso em: 23 de janeiro de 2020.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('FREITAS, Djalma Dias. Acidente de trabalho: causas e suas consequências. Disponível em: http://www.conteudojuridico.com.br/artigo,acidente-de-trabalho-causas-e-suas consequencias,34481.html Acesso em: 23 de julho de 2018.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('FRIEDRICH, C.L. MD. Médico do Trabalho. Editorial - Trabalho eventual/ intermitente/ permanente, 2016. Especialista em Medicina do Trabalho AMB ANAMT. Especialista em Ergonomia. Professor nos Cursos de Medicina do Trabalho e Perícias Médicas IAHCS (Porto Alegre - RS). Professor no Curso de TST FEMA (Santa Rosa - RS). Perito Médico Judicial.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('FUNDACENTRO – Ergonomia - Segurança e Saúde no Trabalho – Saúde Ocupacional. 2. Ergonomia – Condições de Trabalho – Ambiente de Trabalho. I. Titulo. II. Fundacentro, Trad. 2018.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('FUNDACENTRO - Fundação Jorge Duprat Figueiredo de Segurança e Medicina do Trabalho. Norma de Higiene Ocupacional – NHO 01: Avaliação da exposição ocupacional ao ruído. 41 f. Ministério do Trabalho e Emprego - MTBE, Fundacentro. Brasília, 2001.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('GALLOIS, N. S. P. Análise das Condições de Stress e Conforto Térmico Sob Baixas Temperaturas em Indústrias Frigoríficas de Santa Catarina. Dissertação de Mestrado em Engenharia de Produção –UFSC. Florianópolis, 2002. Disponível em: http://www.labeee.ufsc.br/sites/default/files/publicacoes/dissertacoes/DISSERTACAO_Nelson_Simoes_Pires_Gallois.pdf. Acesso em: março 2020.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('LEINFELDER, Robson Rodrigues. Análise de riscos para redução dos riscos de segurança em uma pedreira paulista[doi:10.11606/D.3.2016.tde - 07122016-102503]. São Paulo: Escola Politécnica, Universidade de São Paulo, 2016. Dissertação de Mestrado em Engenharia Mineral. [acesso 2018-08-22].', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('Mendonça, A. L. P. V. Métodos de avaliação de riscos: contributo para a sua aplicabilidade no setor da construção civil. Dissertação (mestrado em Engenharia de Ambiente) – Universidade do Algarve, Algarve, 2013.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('PRESTES, Andréia do R. Modelo de mapa de riscos para serviços de conservação de obras rodoviárias. 2009. 98 f. Monografia (Especialização em Engenharia de Segurança do Trabalho) - Universidade Tecnológica Federal do Paraná. Ponta Grossa, 2009.', $fontStyleReferencias, $paragraphStyle);
$myTextElement = $section->addText('Serviço Social da Indústria - SESI. Departamento Regional da Bahia. Caderno Educativo de Legislação em SST: abordando as NR 5, 7, 9, 15, 16 e o FAP/NTEP. Serviço Social da Indústria - SESI. Departamento Regional da Bahia _ Salvador: Sistema FIEB, 2011.p. 208.', $fontStyleReferencias, $paragraphStyle);
